### ISSUE TITLE
If input passed is not a string, then `fmt.replace` will throw an error

### ISSUE THREAD

**Issue by niftylettuce** [tmpfs/format-util#1]
e.g. `Uncaught TypeError: fmt.replace is not a function`

`util.format` does not throw an error when the input passed is not a String

Ref: <https://github.com/tmpfs/format-util/blob/master/format.js#L32>

**Comment by tmpfs** [comment]
This is expected behavior, see my comment on the PR:

https://github.com/tmpfs/format-util/pull/2

If you can convince me why you need to pass anything other than a string as the format *string* I am willing to reconsider.

**Comment by niftylettuce** [comment]
You should accept this PR, because util.format itself converts toString.

You advertise it as:

> Lightweight util.format() for the browser

But util.format itself converts toString

**Comment by tmpfs** [comment]
Still does not make sense to me and i am not going to do it without a valid justification for why other types should be coerced automatically, personally i think the `TypeError` is more correct.

**Comment by niftylettuce** [comment]
Then don't advertise it's util.format for the browser.

**Comment by tmpfs** [comment]
I have updated the description to reflect that it is not (and never was intended to be) an exact match for `util.format()`.

**Comment by niftylettuce** [comment]
It is super unfortunate I have to maintain a fork now though 😦 

Thank you though for your work on this package
